=== LinkNing/myshowcase/j2se/src/main/java/net/nifoo/tij/dom4j/books.xsd
<?xml version="1.0" encoding="UTF-8" ?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="books">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="book" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="title" type="xs:string" />
						</xs:sequence>
						<xs:attribute name="show" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="yes" />
									<xs:enumeration value="no" />
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
					</xs:complexType>
				</xs:element>

				<xs:element name="owner" type="xs:string" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== LinkNing/myshowcase/j2se/src/main/java/net/nifoo/tij/dom4j/books.xml
<?xml version="1.0"?>
<books xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="books.xsd">
	<!--This is a test for dom4j, holen, 2004.9.11-->
	<book show="yes">
		<title>Dom4j Tutorials</title>
	</book>
	<book show="yes">
		<title>Lucene Studing</title>
	</book>
	<book show="no">
		<title>Lucene in Action</title>
	</book>
	<owner>O'Reilly</owner>
</books>
